config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :products
  resources :cart_items,only:[:destroy]

  get '/cart', to: 'carts#index'
  get '/cart/add', to: 'carts#add'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :cart_items
	belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :cart
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

	
		
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
def destroy

cart_item = CartItem.find(params[:id])

cart_item.destroy

redirect_to cart_path
end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!
	def index
		@cart =	current_user.carts.last
		if @cart.nil?
			@cart = current_user.carts.create
		end
		@cart_items = @cart.cart_items
	end


	def add
			@cart = current_user.carts.last

			if @cart.nil?
					@cart = current_user.carts.create
				end

				@cart.cart_items.create(product_id: params[:product])
				redirect_to '/cart'
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@products = Product.all
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	before_action :authenticate_user!

	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
	end

	def new
		@product = Product.new
	end
	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])

		@product.update(product_params)
		redirect_to product_path(@product)
	end

	def create
		product = Product.create(product_params)
		
		redirect_to products_path
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy

		redirect_to products_path
	end
	
	private 

	def product_params
		params.require(:product).permit(:name, :photo, :description, :price)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/index.html.erb
<div class = "row">
<h1>Cart</h1>
<table class = "table">
<thead>
<tr>
<th scope = "col">No.</th>
<th scope = "col">Product Name</th>
<th scope = "col">Price</th>
<tr>
</thead>
<tbody>
<% @cart_items.each_with_index do |cart_item, index|  %>
<tr>
<td scopes = "row"><%= index + 1 %></td>
<td> <%= cart_item.product.name %> </td>
<td><%= cart_item.product.price %></td>
<td>
<%= link_to 'Delete', cart_item, method: :delete, data: { confirm: 'Are you sure'} %>
</td>
</tr>
<% end %>
</tbody>
</table>
</div>

app/views/home/index.html.erb
<h1>shlor</h1>
<div class="row"><% @products.each do |product|%>
	<div class="col-lg-4 col-md-6 mb-4"> 

		<div class="card h-100">
			<%= image_tag(product.photo, class: "card-img-top", style:"width:100px; margin:auto")unless product.photo.nil? %>
			<div class="card-body">
				<h4><%= product.name %></h4>
				<h5><%= product.price %></h5>
				<p class="card-text"><%= product.description %></p>
			</div>
			<div class="card-footer">
				<%= link_to "Add to cart", cart_add_path(product: product.id),class: 'btn btn-primary' %>
			</div>


		</div>



	</div>.				
	<%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">TumoCanteen</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <%  if user_signed_in? %>
           <li class="nav-item"> 
            <%= link_to("Logout",destroy_user_session_path, method: :delete,class: 'nav-link') %>
            </li>

          <% else %>
          <li class="nav-item">
            <%= link_to("Login",new_user_session_path, class: 'nav-link') %>
            
          </li>
          <li class="nav-item">
            <%= link_to("Signup",new_user_registration_path, class: 'nav-link') %>
            
          </li> 

          <% end %>
        </ul>
      </div>
      </div>
    </nav>
    <div class="container">

    <%= yield %>
      
    </div><button class="">
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product </h1>

<%= form_for @product do |form| %>
	<%= form.label :name %>
	<%= form.text_field :name %>
	<br>
	<%= form.label :photo %>
	<%= form.text_field :photo %>
	<br>
	<%= form.label :description %>
	<%= form.text_field :description %>

	<%= form.label :price %>
	<%= form.text_field :price %>
	<br>
	<%= form.submit%>
	

<% end %>	

app/views/products/index.html.erb
<ul>
	<% @products.each do |product|%>

	<li><%= link_to product.name, product_path(product)%>
		
		<%= link_to 'Edit', edit_product_path(product) %><br>
	<%= image_tag product.photo unless product.photo.nil? %><br>
	<h2><%= product.description %></h2>
		
		<%= link_to 'Delete', product, method: :delete,data:{confirm: "Are you sure?"} %><br>
		
	</li>

</ul>
<% end %>
<%= link_to "New", new_product_path %>
	

app/views/products/new.html.erb
<h1>Create new product </h1>

<%= form_for @product do |form| %>
	<%= form.label :name %>
	<%= form.text_field :name %>
	<br>
	<%= form.label :photo %>
	<%= form.text_field :photo %>
	<br>
	<%= form.label :description %>
	<%= form.text_field :description %>

	<%= form.label :price %>
	<%= form.text_field :price %>
	<br>
	<%= form.submit%>
	

<% end %>	